# A sample Gemfile
source "https://rubygems.org"

gem 'nokogiri', '1.15.6' # Versions higher require ruby 3.0+

gem "rest-client"
gem 'rubyzip', '~>1.3.0' # will load new rubyzip version
gem 'zip-zip' # will load compatibility for old rubyzip API.
gem "addressable"
gem "execjs"
gem "dotenv"