# A sample Gemfile
source "https://rubygems.org"

gem "nokogiri"
gem "uglifier"
gem "rest-client"
gem 'rubyzip', '~>1.3.0' # will load new rubyzip version
gem 'zip-zip' # will load compatibility for old rubyzip API.
gem "addressable"
gem "execjs"
gem "therubyracer"
